# Generated by Django 3.2 on 2021-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_watchlist_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='total_item',
            field=models.IntegerField(default=0),
        ),
    ]
