# Generated by Django 3.2 on 2021-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210424_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist_total',
            name='total_item',
            field=models.IntegerField(default=0),
        ),
    ]
