# Generated by Django 3.2 on 2021-04-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_total_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist_total',
            name='total_item',
            field=models.IntegerField(),
        ),
    ]
