# Generated by Django 3.2 on 2021-04-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_watchlist_total_total_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_total',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
