# Generated by Django 3.2 on 2021-04-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist_total_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchlist_total',
        ),
        migrations.AddField(
            model_name='winner',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
